project_id = "mxjkjvrsvfmgsstunzyv"

[functions.admin-signup]
verify_jwt = false

[functions.suggest-ap]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.delete-user]
verify_jwt = true
